* Introducción

Este repositorio contiene posters que listan fórmulas y expresiones que son comúnmente usadas en los cursos de ciencias del CEPREUNI y en los cursos generales de los primeros ciclos de la Universidad Nacional de Ingeniería.

El objetivo de estos posters es ayudar a los estudiantes del CEPREUNI y la Universidad Nacional de Ingeniería a memorizar esas fórmulas y expresiones. Esto lo logramos listándolas de manera ordenada y clara.

* ¿Cómo contribuir?

2 maneras:

1. Reporta algún error en algún poster o sugiere una mejora creando un *issue* en este repositorio
   + Para hacer esto, necesitas crear una cuenta de Github. Luego de crear la cuenta, visitar [[https://github.com/rodrigo-morales-1/posters-uni-peru][este repositorio]], ir a la ventana *Issues* y presionar en "*New Issue*"
   + Hacer esto es similar a crear una publicación en un foro de Internet
2. Proponer un cambio en el código haciendo un *pull request*
   + Para hacer esto, necesitas tener conocimientos del comando =git= y como hacer un *pull request* en Github. Además, necesitas saber el lenguaje de marcado LaTeX. LaTeX es el lenguaje que ha sido usado para crear
